"""Master list of Indian cities for the searchable From/To route dropdowns.
Covers state/UT capitals plus major and tier-2/3 cities and towns.

PRIORITY_CITIES (Odisha, Jharkhand, West Bengal, Bihar) are surfaced first in
the dropdown. Both are plain sorted tuples, reusable without a DB hit."""

INDIAN_CITIES = (
    "Adilabad",
    "Adityapur",
    "Adoni",
    "Agartala",
    "Agra",
    "Ahmedabad",
    "Ahmednagar",
    "Aizawl",
    "Ajmer",
    "Akola",
    "Alappuzha (Alleppey)",
    "Aligarh",
    "Alipurduar",
    "Allahabad (Prayagraj)",
    "Almora",
    "Alwar",
    "Ambala",
    "Ambikapur",
    "Amravati",
    "Amreli",
    "Amritsar",
    "Anand",
    "Anandapur",
    "Anantapur",
    "Anantnag",
    "Angul",
    "Ankleshwar",
    "Araria",
    "Arrah (Ara)",
    "Asansol",
    "Aska",
    "Aurangabad",
    "Aurangabad (Bihar)",
    "Ayodhya",
    "Azamgarh",
    "Bagaha",
    "Bagalkot",
    "Baharampur (Berhampore)",
    "Bahraich",
    "Bakhtiarpur",
    "Balaghat",
    "Balangir",
    "Balasore (Baleshwar)",
    "Ballari (Bellary)",
    "Balurghat",
    "Banka",
    "Bankura",
    "Bansberia",
    "Banswara",
    "Baranagar",
    "Barasat",
    "Barbigha",
    "Barbil",
    "Bardhaman (Burdwan)",
    "Bareilly",
    "Bargarh",
    "Barh",
    "Barhi",
    "Baripada",
    "Barmer",
    "Barnala",
    "Barpeta",
    "Barrackpore",
    "Basirhat",
    "Basti",
    "Bathinda",
    "Beed",
    "Begusarai",
    "Belagavi (Belgaum)",
    "Belpahar",
    "Bengaluru",
    "Berhampur (Brahmapur)",
    "Bettiah",
    "Betul",
    "Bhabua",
    "Bhadrak",
    "Bhagalpur",
    "Bharatpur",
    "Bharuch",
    "Bhatpara",
    "Bhavnagar",
    "Bhawanipatna",
    "Bhilai",
    "Bhilwara",
    "Bhimavaram",
    "Bhind",
    "Bhiwandi",
    "Bhiwani",
    "Bhopal",
    "Bhubaneswar",
    "Bhuj",
    "Bidar",
    "Bidhannagar (Salt Lake)",
    "Bihar Sharif",
    "Bijapur (Vijayapura)",
    "Bijnor",
    "Bikaner",
    "Bilaspur",
    "Bokaro",
    "Bolpur (Santiniketan)",
    "Bongaigaon",
    "Bongaon",
    "Boudh",
    "Brajrajnagar",
    "Budaun",
    "Bulandshahr",
    "Buldhana",
    "Bundi",
    "Bundu",
    "Buxar",
    "Byasanagar",
    "Chaibasa",
    "Chakdaha",
    "Chakradharpur",
    "Chamba",
    "Chandannagar",
    "Chandigarh",
    "Chandrapur",
    "Changanassery",
    "Charkhi Dadri",
    "Chatra",
    "Chengalpattu",
    "Chennai",
    "Chhapra",
    "Chhatarpur",
    "Chhatrapur",
    "Chhindwara",
    "Chikkamagaluru (Chikmagalur)",
    "Chilakaluripet",
    "Chirkunda",
    "Chitradurga",
    "Chittoor",
    "Chittorgarh",
    "Coimbatore",
    "Contai (Kanthi)",
    "Cooch Behar",
    "Cuddalore",
    "Cuttack",
    "Dahod",
    "Daltonganj (Medininagar)",
    "Daman",
    "Damoh",
    "Danapur",
    "Dankuni",
    "Darbhanga",
    "Darjeeling",
    "Davanagere",
    "Dehradun",
    "Dehri",
    "Deogarh (Debagarh)",
    "Deoghar",
    "Dewas",
    "Dhamtari",
    "Dhanbad",
    "Dhar",
    "Dharmapuri",
    "Dharwad",
    "Dhenkanal",
    "Dholpur",
    "Dhule",
    "Dhulian",
    "Dibrugarh",
    "Dimapur",
    "Dindigul",
    "Dinhata",
    "Diu",
    "Dum Dum",
    "Dumka",
    "Dungarpur",
    "Durg",
    "Durgapur",
    "Eluru",
    "Erode",
    "Etawah",
    "Faizabad",
    "Faridabad",
    "Faridkot",
    "Farrukhabad",
    "Fatehpur",
    "Fazilka",
    "Firozabad",
    "Firozpur",
    "Forbesganj",
    "Gadag",
    "Gandhidham",
    "Gandhinagar",
    "Gangarampur",
    "Gangtok",
    "Garhwa",
    "Gaya",
    "Ghaziabad",
    "Ghazipur",
    "Giridih",
    "Godda",
    "Godhra",
    "Gonda",
    "Gondia",
    "Gopalganj",
    "Gorakhpur",
    "Gudivada",
    "Gulbarga (Kalaburagi)",
    "Gumla",
    "Guna",
    "Guntakal",
    "Guntur",
    "Gunupur",
    "Gurdaspur",
    "Gurugram (Gurgaon)",
    "Guwahati",
    "Gwalior",
    "Habra",
    "Hajipur",
    "Haldia",
    "Haldwani",
    "Halisahar",
    "Hamirpur",
    "Hanumangarh",
    "Hapur",
    "Hardoi",
    "Haridwar",
    "Hassan",
    "Hathras",
    "Hazaribagh",
    "Hindupur",
    "Hinjilicut",
    "Hisar",
    "Hooghly",
    "Hoshangabad (Narmadapuram)",
    "Hoshiarpur",
    "Hospet (Hosapete)",
    "Hosur",
    "Howrah",
    "Hubballi (Hubli)",
    "Hussainabad",
    "Hyderabad",
    "Ichalkaranji",
    "Imphal",
    "Indore",
    "Islampur",
    "Itanagar",
    "Jabalpur",
    "Jagatsinghpur",
    "Jagdalpur",
    "Jagdishpur",
    "Jaipur",
    "Jaisalmer",
    "Jajpur",
    "Jalandhar",
    "Jalgaon",
    "Jalna",
    "Jalpaiguri",
    "Jamalpur",
    "Jammu",
    "Jamnagar",
    "Jamshedpur",
    "Jamtara",
    "Jamui",
    "Jangipur",
    "Jaunpur",
    "Jehanabad",
    "Jeypore",
    "Jhansi",
    "Jhargram",
    "Jharsuguda",
    "Jhumri Telaiya",
    "Jhunjhunu",
    "Jind",
    "Joda",
    "Jodhpur",
    "Jorhat",
    "Junagadh",
    "Kadapa",
    "Kaithal",
    "Kakinada",
    "Kalimpong",
    "Kalyan-Dombivli",
    "Kamarhati",
    "Kanchipuram",
    "Kanchrapara",
    "Kanker",
    "Kannur",
    "Kanpur",
    "Kantabanji",
    "Kanyakumari",
    "Kapurthala",
    "Karaikudi",
    "Karimnagar",
    "Karnal",
    "Karur",
    "Karwar",
    "Kasaragod",
    "Kashipur",
    "Kathua",
    "Katihar",
    "Katni",
    "Katwa",
    "Kavaratti",
    "Kendrapara",
    "Kendujhar (Keonjhar)",
    "Khagaria",
    "Khammam",
    "Khandwa",
    "Khanna",
    "Kharagpur",
    "Khargone",
    "Khordha",
    "Khunti",
    "Kishanganj",
    "Kochi (Cochin)",
    "Koderma",
    "Kohima",
    "Kolar",
    "Kolhapur",
    "Kolkata",
    "Kollam",
    "Koraput",
    "Korba",
    "Kota",
    "Kothagudem",
    "Kottayam",
    "Kozhikode (Calicut)",
    "Krishnagiri",
    "Krishnanagar",
    "Kullu",
    "Kumbakonam",
    "Kurnool",
    "Kurukshetra",
    "Lakhimpur",
    "Lakhisarai",
    "Latehar",
    "Latur",
    "Leh",
    "Lohardaga",
    "Lucknow",
    "Ludhiana",
    "Lunglei",
    "Machilipatnam",
    "Madanapalle",
    "Madhepura",
    "Madhubani",
    "Madhupur",
    "Madhyamgram",
    "Madikeri",
    "Madurai",
    "Mahbubnagar",
    "Malda (English Bazar)",
    "Malegaon",
    "Malkangiri",
    "Mandi",
    "Mandsaur",
    "Mandya",
    "Maner",
    "Mangaluru (Mangalore)",
    "Manipal",
    "Mathura",
    "Mau",
    "Medinipur (Midnapore)",
    "Meerut",
    "Mehsana",
    "Mihijam",
    "Mirzapur",
    "Moga",
    "Mokama",
    "Moradabad",
    "Morbi",
    "Morena",
    "Motihari",
    "Mughalsarai",
    "Muktsar",
    "Mumbai",
    "Munger",
    "Muzaffarnagar",
    "Muzaffarpur",
    "Mysuru (Mysore)",
    "Nabadwip",
    "Nabarangpur",
    "Nabha",
    "Nadiad",
    "Nagaon",
    "Nagaur",
    "Nagercoil",
    "Nagpur",
    "Naihati",
    "Nainital",
    "Nalgonda",
    "Namakkal",
    "Nanded",
    "Nandurbar",
    "Nandyal",
    "Narkatiaganj",
    "Narnaul",
    "Nashik",
    "Navi Mumbai",
    "Navsari",
    "Nawada",
    "Nayagarh",
    "Neemuch",
    "Nellore",
    "New Delhi",
    "Nizamabad",
    "Noida",
    "Ongole",
    "Ooty (Udhagamandalam)",
    "Orai",
    "Osmanabad (Dharashiv)",
    "Pakur",
    "Palakkad",
    "Palampur",
    "Palanpur",
    "Pali",
    "Panaji (Panjim)",
    "Panchkula",
    "Panihati",
    "Panipat",
    "Panvel",
    "Paradip",
    "Paralakhemundi",
    "Parbhani",
    "Pathanamthitta",
    "Pathankot",
    "Patiala",
    "Patna",
    "Pattamundai",
    "Phulbani",
    "Phusro",
    "Pilibhit",
    "Pimpri-Chinchwad",
    "Pondicherry (Puducherry)",
    "Porbandar",
    "Port Blair",
    "Proddatur",
    "Pune",
    "Puri",
    "Purnia",
    "Purulia",
    "Raebareli",
    "Raghunathpur",
    "Raichur",
    "Raiganj",
    "Raigarh",
    "Raipur",
    "Rajahmundry",
    "Rajgangpur",
    "Rajgir",
    "Rajkot",
    "Rajnandgaon",
    "Rajpura",
    "Ramagundam",
    "Rameswaram",
    "Ramgarh",
    "Rampur",
    "Ranaghat",
    "Ranchi",
    "Ratlam",
    "Ratnagiri",
    "Raxaul",
    "Rayagada",
    "Rewa",
    "Rewari",
    "Rishikesh",
    "Rishra",
    "Rohtak",
    "Roorkee",
    "Rourkela",
    "Rudrapur",
    "Sagar",
    "Saharanpur",
    "Saharsa",
    "Sahibganj",
    "Salem",
    "Samastipur",
    "Sambalpur",
    "Sambhal",
    "Sangli",
    "Sangrur",
    "Santipur",
    "Saraikela",
    "Sasaram",
    "Satara",
    "Satna",
    "Sawai Madhopur",
    "Secunderabad",
    "Sehore",
    "Seoni",
    "Serampore",
    "Shahjahanpur",
    "Sheikhpura",
    "Sheohar",
    "Shillong",
    "Shimla",
    "Shimoga (Shivamogga)",
    "Shivpuri",
    "Sikar",
    "Silchar",
    "Siliguri",
    "Silvassa",
    "Simdega",
    "Singrauli",
    "Sirsa",
    "Sitamarhi",
    "Sitapur",
    "Sivakasi",
    "Siwan",
    "Solapur",
    "Sonepur (Subarnapur)",
    "Sonipat",
    "Soro",
    "Srikakulam",
    "Srinagar",
    "Sultanpur",
    "Sundargarh",
    "Supaul",
    "Surat",
    "Surendranagar",
    "Suri",
    "Tadepalligudem",
    "Talcher",
    "Tamluk",
    "Tenali",
    "Tezpur",
    "Thane",
    "Thanjavur",
    "Theni",
    "Thiruvananthapuram (Trivandrum)",
    "Thoothukudi (Tuticorin)",
    "Thrissur",
    "Tinsukia",
    "Tiruchirappalli (Trichy)",
    "Tirunelveli",
    "Tirupati",
    "Tiruppur",
    "Tiruvannamalai",
    "Titagarh",
    "Titlagarh",
    "Tonk",
    "Tumakuru (Tumkur)",
    "Udaipur",
    "Udupi",
    "Ujjain",
    "Uluberia",
    "Una",
    "Unnao",
    "Vadodara",
    "Valsad",
    "Vapi",
    "Varanasi",
    "Vasai-Virar",
    "Vellore",
    "Veraval",
    "Vidisha",
    "Vijayawada",
    "Villupuram",
    "Virudhunagar",
    "Visakhapatnam (Vizag)",
    "Vizianagaram",
    "Warangal",
    "Wardha",
    "Yamunanagar",
    "Yavatmal",
)

PRIORITY_CITIES = (
    "Adityapur",
    "Alipurduar",
    "Anandapur",
    "Angul",
    "Araria",
    "Arrah (Ara)",
    "Asansol",
    "Aska",
    "Aurangabad (Bihar)",
    "Bagaha",
    "Baharampur (Berhampore)",
    "Bakhtiarpur",
    "Balangir",
    "Balasore (Baleshwar)",
    "Balurghat",
    "Banka",
    "Bankura",
    "Bansberia",
    "Baranagar",
    "Barasat",
    "Barbigha",
    "Barbil",
    "Bardhaman (Burdwan)",
    "Bargarh",
    "Barh",
    "Barhi",
    "Baripada",
    "Barrackpore",
    "Basirhat",
    "Begusarai",
    "Belpahar",
    "Berhampur (Brahmapur)",
    "Bettiah",
    "Bhabua",
    "Bhadrak",
    "Bhagalpur",
    "Bhatpara",
    "Bhawanipatna",
    "Bhubaneswar",
    "Bidhannagar (Salt Lake)",
    "Bihar Sharif",
    "Bokaro",
    "Bolpur (Santiniketan)",
    "Bongaon",
    "Boudh",
    "Brajrajnagar",
    "Bundu",
    "Buxar",
    "Byasanagar",
    "Chaibasa",
    "Chakdaha",
    "Chakradharpur",
    "Chandannagar",
    "Chatra",
    "Chhapra",
    "Chhatrapur",
    "Chirkunda",
    "Contai (Kanthi)",
    "Cooch Behar",
    "Cuttack",
    "Daltonganj (Medininagar)",
    "Danapur",
    "Dankuni",
    "Darbhanga",
    "Darjeeling",
    "Dehri",
    "Deogarh (Debagarh)",
    "Deoghar",
    "Dhanbad",
    "Dhenkanal",
    "Dhulian",
    "Dinhata",
    "Dum Dum",
    "Dumka",
    "Durgapur",
    "Forbesganj",
    "Gangarampur",
    "Garhwa",
    "Gaya",
    "Giridih",
    "Godda",
    "Gopalganj",
    "Gumla",
    "Gunupur",
    "Habra",
    "Hajipur",
    "Haldia",
    "Halisahar",
    "Hazaribagh",
    "Hinjilicut",
    "Hooghly",
    "Howrah",
    "Hussainabad",
    "Islampur",
    "Jagatsinghpur",
    "Jagdishpur",
    "Jajpur",
    "Jalpaiguri",
    "Jamalpur",
    "Jamshedpur",
    "Jamtara",
    "Jamui",
    "Jangipur",
    "Jehanabad",
    "Jeypore",
    "Jhargram",
    "Jharsuguda",
    "Jhumri Telaiya",
    "Joda",
    "Kalimpong",
    "Kamarhati",
    "Kanchrapara",
    "Kantabanji",
    "Katihar",
    "Katwa",
    "Kendrapara",
    "Kendujhar (Keonjhar)",
    "Khagaria",
    "Kharagpur",
    "Khordha",
    "Khunti",
    "Kishanganj",
    "Koderma",
    "Kolkata",
    "Koraput",
    "Krishnanagar",
    "Lakhisarai",
    "Latehar",
    "Lohardaga",
    "Madhepura",
    "Madhubani",
    "Madhupur",
    "Madhyamgram",
    "Malda (English Bazar)",
    "Malkangiri",
    "Maner",
    "Medinipur (Midnapore)",
    "Mihijam",
    "Mokama",
    "Motihari",
    "Munger",
    "Muzaffarpur",
    "Nabadwip",
    "Nabarangpur",
    "Naihati",
    "Narkatiaganj",
    "Nawada",
    "Nayagarh",
    "Pakur",
    "Panihati",
    "Paradip",
    "Paralakhemundi",
    "Patna",
    "Pattamundai",
    "Phulbani",
    "Phusro",
    "Puri",
    "Purnia",
    "Purulia",
    "Raghunathpur",
    "Raiganj",
    "Rajgangpur",
    "Rajgir",
    "Ramgarh",
    "Ranaghat",
    "Ranchi",
    "Raxaul",
    "Rayagada",
    "Rishra",
    "Rourkela",
    "Saharsa",
    "Sahibganj",
    "Samastipur",
    "Sambalpur",
    "Santipur",
    "Saraikela",
    "Sasaram",
    "Serampore",
    "Sheikhpura",
    "Sheohar",
    "Siliguri",
    "Simdega",
    "Sitamarhi",
    "Siwan",
    "Sonepur (Subarnapur)",
    "Soro",
    "Sundargarh",
    "Supaul",
    "Suri",
    "Talcher",
    "Tamluk",
    "Titagarh",
    "Titlagarh",
    "Uluberia",
)
